version: '2'
services:
    materialthemecheck-app:
        image: materialthemecheck
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://materialthemecheck-mysql:3306/materialthemecheck?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=materialthemecheck-elasticsearch:9300
        ports:
            - 8080:8080
    materialthemecheck-mysql:
        extends:
            file: mysql.yml
            service: materialthemecheck-mysql
    materialthemecheck-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: materialthemecheck-elasticsearch
